### PR TITLE
change deployment target to iOS 9 to fix Archiving with Xcode 12

### PR DESCRIPTION
**Pull request by dvshelley**

### CODE REVIEW

**Comment by simonyangme** [comment]
@matej any chance you can take a look at this PR? iOS 8 is no longer supported as a deployment target with Xcode 12's release.

**Comment by tinder-owenthomas** [comment]
Bump for this one. We cannot upgrade to Xcode 12 until this warning can be silenced. Any chance of getting this merged and a new version released?

**Comment by matej** [comment]
This is pretty easy to work around by adding something like the following in your pod file:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end
```

I use that myself. 

That being said, I think it's fine to jump to V9. Based on a quick check, I don't see any new warnings.

**Comment by tinder-owenthomas** [comment]
@matej I think it needs to be updated here as well https://github.com/jdg/MBProgressHUD/blob/master/MBProgressHUD.podspec#L15

**Pull request merged**
