### PR TITLE
Add a button on the progress view.

### PR DESCRIPTION
**Pull request by m-nakada**
Hi, 

I want to cancel uploading/downloading URL session.
So, I added the button to the progress view.

thanks.

ios simulator screen shot 2014 09 06 15 51 50

### CODE REVIEW

**Comment by matej** [comment]
Something like this is now part of the class in the latest version.

**Comment by m-nakada** [comment]
:+1:

**Comment by misakik** [comment]
:+1:

**Comment by Spettacolo83** [comment]
Sorry but I didn't find on the latest version the delegate when the button is pressed.
Can you help me? Thank you very much!

**Pull request closed without merging**
