### PR TITLE
for you add beauty

### PR DESCRIPTION
**Pull request by fancyLi**
Please forgive me, the first attempt to use github, thanks to satisfy my seeking knowledge desire

### CODE REVIEW

**Comment by rossbeale** [comment]
+1

**Comment by schraeds** [comment]
The force is strong in this one;  syntax issues tho

**Comment by dedg3** [comment]
made my day <3

**Comment by pronebird** [comment]
Master, I hope your knowledge seeking desire has been satisfied.

**Comment by fancyLi** [comment]
It's been a lot of fun here

**Comment by xuki** [comment]
This gonna get merged, right?

**Comment by pronebird** [comment]
@xuki this is going to be used on first of april instead of checkmark icon.

**Comment by fancyLi** [comment]
> xuki commented 3 minutes ago

hello , i firstly try use github

**Comment by fancyLi** [comment]
> Master

thank you

**Comment by Sefford** [comment]
Senpai

**Comment by dataxpress** [comment]
LGTM

**Comment by matej** [comment]
Ok, I think that's enough. :)

**Pull request closed without merging**
